export const UPDATE_ACTIVE_ITEM = "UPDATE_ACTIVE_ITEM";
export const UPDATE_EDUCATION_INFO = "UPDATE_EDUCATION_INFO";
export const UPDATE_ACTIVE_TECH_SKILL_TAB = "UPDATE_ACTIVE_TECH_SKILL_TAB";
export const UPDATE_LANGUAGE_INFO = "UPDATE_LANGUAGE_INFO";
export const UPDATE_TECHNFRAMEWORK_INFO = "UPDATE_TECHNFRAMEWORK_INFO"
export const UPDATE_OS_INFO = "UPDATE_OS_INFO"
export const UPDATE_SOFTWARE_INFO = "UPDATE_SOFTWARE_INFO"